### ISSUE TITLE
Use pyniryo on niryo one robot

### ISSUE THREAD

**Issue by MADONOKOUKI** [NiryoRobotics/pyniryo#1]
Hi, I'm trying to use pyniryo on niryo one robot using the example code. (Just change variable name ned to niryo_one)
```
from pyniryo import *

niryo_one = NiryoRobot("192.168.0.172")

niryo_one.calibrate_auto()

niryo_one.move_joints(0.2, -0.3, 0.1, 0.0, 0.5, -0.8)
```

However, I got the error below. Simply I assumed that this may not be used on niryo one robot.

Can I fix it ?

```
Connected to server (192.168.0.172) on port: 40001

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    ned.move_joints(0.2, -0.3, 0.1, 0.0, 0.5, -0.8)
  File "/Users/madorin/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/pyniryo/api/tcp_client.py", line 427, in move_joints
    self.__send_n_receive(Command.MOVE_JOINTS, *joints)
  File "/Users/madorin/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/pyniryo/api/tcp_client.py", line 152, in __send_n_receive
    return self.__receive_answer(with_payload=with_payload)
  File "/Users/madorin/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/pyniryo/api/tcp_client.py", line 134, in __receive_answer
    answer_status = received_dict["status"]
KeyError: 'status'

Disconnected from robot
```

**Comment by MADONOKOUKI** [comment]
This problem can be solved if I can get  "status" value from niryo one robot. However, I'm not sure how to get it.

**Comment by remi2257** [comment]
PyNiryo is made to control Niryo Ned not Niryo One. Packet send through TCP are not the same used by Niryo One, so you won't be able to command Niryo One with PyNiryo
