### ISSUE TITLE
Pip install on niryo one robot

### ISSUE THREAD

**Issue by MADONOKOUKI** [NiryoRobotics/pyniryo#2]
Hi, I'm trying to install this package directly on niryo one robot.
I know that niryo one is designed with python 2.7 scripts.
This may lead to an installation error. Do you know any solution to solve it?
I think this problem happens when we install the pyniryo on python 2.7/
```
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-BYy5YX/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.11.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"''
       cwd: None
  Complete output (128 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
  Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8"' don't match your environment
  Collecting setuptools
    Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting scikit-build
    Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
  Collecting cmake
    Using cached cmake-3.18.4.post1.tar.gz (28 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting pip
    Using cached pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
  Collecting distro
    Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
  Collecting packaging
    Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
  Collecting pyparsing>=2.0.2
    Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
  Building wheels for collected packages: cmake
    Building wheel for cmake (PEP 517): started
    Building wheel for cmake (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpiYN7a1
         cwd: /tmp/pip-install-k4RVLf/cmake
    Complete output (88 lines):
    Not searching for unused variables given on the command line.
    CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-k4RVLf/cmake/_cmake_test_compile/build
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
      CMake 3.6 or higher is required.  You are running version 3.5.1
  
  
    -- Configuring incomplete, errors occurred!
      File "/tmp/pip-build-env-FlvNX7/overlay/lib/python2.7/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
        languages=cmake_languages
      File "/tmp/pip-build-env-FlvNX7/overlay/lib/python2.7/site-packages/skbuild/cmaker.py", line 240, in configure
        os.path.abspath(CMAKE_BUILD_DIR())))
  
  
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - failure
    --------------------------------------------------------------------------------
  
  
  
    --------------------------------------------------------------------------------
    -- Trying "Unix Makefiles" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Unix Makefiles" generator - success
    --------------------------------------------------------------------------------
  
    Configuring Project
      Working directory:
        /tmp/pip-install-k4RVLf/cmake/_skbuild/linux-armv7l-2.7/cmake-build
      Command:
        cmake /tmp/pip-install-k4RVLf/cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-k4RVLf/cmake/_skbuild/linux-armv7l-2.7/cmake-install/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python -DPYTHON_VERSION_STRING:STRING=2.7.12 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython2.7.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-FlvNX7/overlay/lib/python2.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  
    Traceback (most recent call last):
  
    An error occurred while configuring with CMake.
      Command:
        cmake /tmp/pip-install-k4RVLf/cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-k4RVLf/cmake/_skbuild/linux-armv7l-2.7/cmake-install/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python -DPYTHON_VERSION_STRING:STRING=2.7.12 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython2.7.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-FlvNX7/overlay/lib/python2.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
      Source directory:
        /tmp/pip-install-k4RVLf/cmake
      Working directory:
        /tmp/pip-install-k4RVLf/cmake/_skbuild/linux-armv7l-2.7/cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
    ERROR: Failed building wheel for cmake
  Failed to build cmake
  ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly
  WARNING: You are using pip version 20.3.3; however, version 20.3.4 is available.
  You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-BYy5YX/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.11.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"'' Check the logs for full command output.
```

**Comment by remi2257** [comment]
PyNiryo is made to control Niryo Ned not Niryo One
