### ISSUE TITLE
Image capture shows payload error for Niryo Ned 2

### ISSUE THREAD

**Issue by pranavrnair22** [NiryoRobotics/pyniryo#7]
#Unable to capture image through the robot's camera

#here is the code: 

img_compressed = robot.get_img_compressed()

img = uncompress_image(img_compressed)

Displaying
show_img_and_wait_close("img_stream", img)

#Error:

Traceback (most recent call last):
  File "c:\Pers\PES\Subjects\MARS\final\camera.py", line 7, in <module>
    img_compressed = robot.get_img_compressed()
  File "C:\Users\PN\AppData\Local\Programs\Python\Python310\lib\site-packages\pyniryo\api\tcp_client.py", line 1302, in get_img_compressed
    _, img = self.__send_n_receive(Command.GET_IMAGE_COMPRESSED, with_payload=True)
  File "C:\Users\PN\AppData\Local\Programs\Python\Python310\lib\site-packages\pyniryo\api\tcp_client.py", line 152, in __send_n_receive
    return self.__receive_answer(with_payload=with_payload)
  File "C:\Users\PN\AppData\Local\Programs\Python\Python310\lib\site-packages\pyniryo\api\tcp_client.py", line 128, in __receive_answer
    received_dict, payload = receive_dict_w_payload(sckt=self.__client_socket)
  File "C:\Users\PN\AppData\Local\Programs\Python\Python310\lib\site-packages\pyniryo\api\communication_functions.py", line 60, in receive_dict_w_payload
    payload_size = dict_data["payload_size"]
KeyError: 'payload_size'

Disconnected from robot

**Comment by jmottier-niryo** [comment]
Hello, this is a known issue and it will be fixed in the next release
